// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pb/echo-service.proto

package echo_service

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _echo_service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on EchoMessage with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *EchoMessage) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetValue()) < 3 {
		return EchoMessageValidationError{
			field:  "Value",
			reason: "value length must be at least 3 bytes",
		}
	}

	return nil
}

// EchoMessageValidationError is the validation error returned by
// EchoMessage.Validate if the designated constraints aren't met.
type EchoMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EchoMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EchoMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EchoMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EchoMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EchoMessageValidationError) ErrorName() string { return "EchoMessageValidationError" }

// Error satisfies the builtin error interface
func (e EchoMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEchoMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EchoMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EchoMessageValidationError{}
